[package]
name = "ruzstd"
version = "0.2.2"
authors = ["Moritz Borcherding <moritz.borcherding@web.de>"]
edition = "2018"
license = "MIT"
homepage = "https://github.com/KillingSpark/zstd-rs"
repository = "https://github.com/KillingSpark/zstd-rs"
description = "A decoder for the zstd compression format"
exclude = ["decodecorpus_files/*", "dict_tests/*", "fuzz_decodecorpus/*"]
readme = "Readme.md"

[dependencies]
byteorder = "1.3.4"
twox-hash = { version = "1.6.0", default-features = false }

[dev-dependencies]
criterion = "0.3"
rand = "*"

[[bench]]
name = "reversedbitreader_bench"
harness = false